// Angular/src/app/game/game/game.component.ts
import { Component, OnInit } from '@angular/core';

import { ActivatedRoute } from '@angular/router';
import { StateService, State } from './../state.service';
import { MyhttpService } from './../../myhttp.service';
import { Observable } from 'rxjs/Rx';

@Component({
  selector: 'app-game',
  templateUrl: './game.component.html',
  styleUrls: ['./game.component.css']
})
export class GameComponent implements OnInit {

	private _status: string = 'fetching';

	private _stateService: StateService;

	private _playerName: string;

	private _myhttpservice: MyhttpService;

	_handleSubmitClick() {
		this._stateService.state.player_name = this._playerName;
	}

	_handleSaveClick() {
		this._myhttpservice.postGame(this._stateService.state)
		.subscribe(
			data => {
		      console.log("Response: ", data);
			},
			error => {
			  console.error("Error saving game!");
			  return Observable.throw(error);
			}
		 );
	}

  constructor(route: ActivatedRoute, stateService: StateService, myhttpService: MyhttpService) {
	this._stateService = stateService;
	this._myhttpservice = myhttpService;

  	if (route.snapshot.data.continue) {
  		myhttpService.getSavedGame().subscribe((state:State) => {
  			stateService.state = state;
  			this._status = 'success';
  		}, error => {
  			this._status = error.statusText;
  		});
  	} else {
  		stateService.reset();
  		this._status = 'success';
  	}
  }

  ngOnInit() {
  }
}

<div *ngIf="_status == 'fetching'" class="loader"></div>

<form *ngIf="(_stateService.state$ | async).player_name === ''">
	<label>Introduce Player Name:</label>
	<input [(ngModel)]="_playerName" type="text" name="_playerName">
	<input (click)="_handleSubmitClick()" type="submit" value="Submit"/>
</form>

<div *ngIf="_status == 'success' && (_stateService.state$ | async).player_name !== ''">
	<app-header></app-header>
	<app-board></app-board>
	<form>
      <input (click)="_handleSaveClick()" type="submit" value="Save"/>
    </form>
</div>

<h3 *ngIf="_status !== 'success' && _status !== 'fetching'">Error getting state from server. The error was: {{ _status }}</h3>

// react-ttt/src/components/Tictactoe/Game.jsx
import React from 'react';
import Header from './Header.jsx';
import Board from './Board.jsx';
import { connect } from 'react-redux';
import { playPosition, fetchState, newPlayer, resetPlayer } from './../../reducers/actions';

class Game extends React.Component {
  constructor(props) {
    super(props);
    this.state = {player_name: ""};
    this.appClick = this.appClick.bind(this);
    this.handlePlayerInputChange = this.handlePlayerInputChange.bind(this);
    this.handlePlayerSubmit = this.handlePlayerSubmit.bind(this);
  }
  appClick(rowNumber, columnNumber) {
      this.props.dispatch(playPosition(rowNumber, columnNumber, this.props.turn, this.props.values));
  }
  handlePlayerInputChange(event){
    this.setState({player_name: event.target.value});
  }
  handlePlayerSubmit(event) {
    console.log('A name was submitted: ' + this.state.player_name);
    event.preventDefault();
    this.props.dispatch(newPlayer(this.state.player_name));
  }
  componentDidMount(){
    console.log("componentDidMount");
    if(this.props.continue===true){
      this.props.dispatch(fetchState());
    } else {
      this.props.dispatch(resetPlayer());
    }
  }
  render() {
    if(this.props.fetch.fetching){
      return <div className="loader"></div>;
    } else if(this.props.fetch.fetching===false && this.props.fetch.error){
      console.log(this.props.fetch.error);
      return <h3>Error getting state from server. The error was: {this.props.fetch.error.toString()}</h3>;
    }else{
      if(this.props.player_name!==""){
          let welcome_text = "Welcome " + this.props.player_name;
          let text = "Turn of " + this.props.turn;
          return (
            <div>
              <Header text={text} welcome_text={welcome_text}/>
              <Board values={this.props.values}  appClick={this.appClick} />
            </div>
          );
      } else {
          return (<header className="header">
            <form onSubmit={this.handlePlayerSubmit}>
              <label>
                Introduce Player Name:
                <input type="text" value={this.state.player_name} onChange={this.handlePlayerInputChange} />
                <input type="submit" value="Submit" />
              </label>
            </form>
          </header>
        );
      }
    }
  }
}

function mapStateToProps(state) {
    return {
        values: state.values,
        turn: state.turn,
        fetch: state.fetch,
        player_name: state.player_name
    };
}
export default connect(mapStateToProps)(Game);
